'use client';

import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Menu, X } from 'lucide-react';

const projects = [
  ['01', 'Move My Stuff', 'Logistics Operations Platform', 'A connected platform spanning onboarding, bookings, routes, zones, capacity, pricing, finance, and integrations.', ['Logistics', 'ERP', 'Requirements', 'UAT']],
  ['02', 'Koala Marketing Cloud', 'Marketing Automation Platform', 'Customer engagement across signup forms, dynamic segments, profiles, consent, and behaviour-based campaigns.', ['MarTech', 'Segmentation', 'Customer Data']],
  ['03', 'Worksbuddy', 'Unified Business SaaS Ecosystem', 'Five connected modules—CRM, tasks, invoicing, e-signatures, and email marketing—delivered as one ecosystem.', ['SaaS', 'CRM', 'SSO', 'Agile']],
  ['04', 'AI-Native ERP & POS', 'Product Strategy and Platform Concept', 'A controlled AI-assisted path from natural-language requirements through testing, approval, and versioned release.', ['AI', 'ERP', 'POS', 'Strategy']],
  ['05', 'AI Office Analytics', 'Computer-Vision Proof of Concept', 'Privacy-conscious occupancy and space analytics using anonymous person detection—never facial recognition.', ['Computer Vision', 'Analytics', 'Privacy']],
] as const;
const strengths = [
  ['01', 'Requirements teams can build', 'Turning conversations into workflows, user stories, edge cases, validation rules, and testable acceptance criteria.'],
  ['02', 'Cross-functional alignment', 'Keeping stakeholders, design, engineering, QA, and leadership aligned around decisions and dependencies.'],
  ['03', 'Delivery with control', 'Creating visible priorities, practical sprint plans, UAT readiness, release discipline, and focused stabilization.'],
  ['04', 'Systems-level thinking', 'Seeing how modules, users, data, permissions, integrations, and operations affect the whole platform.'],
];
const projectImages = [
  ['/projects/move-my-stuff.png','Dark logistics route network connecting depots and customer locations'],
  ['/projects/koala-marketing-cloud.png','Customer signals flowing into profiles, segments, and campaigns'],
  ['/projects/worksbuddy-dashboard.png','Official Worksbuddy software dashboard showing one connected workspace'],
  ['/projects/ai-erp-pos.png','AI request progressing through test and approval gates into a versioned release'],
  ['/projects/ai-office-analytics.png','Privacy-conscious office occupancy zones and anonymous detection markers'],
] as const;

export default function Home() {
  const [menu, setMenu] = useState(false), [study, setStudy] = useState<number | null>(null), [loader, setLoader] = useState(false), [scrolled, setScrolled] = useState(false);
  useEffect(() => { const first = !sessionStorage.getItem('nc-intro'); sessionStorage.setItem('nc-intro', '1'); const start = requestAnimationFrame(() => setLoader(first)); const t = setTimeout(() => setLoader(false), 1550); const scroll = () => setScrolled(scrollY > 40); addEventListener('scroll', scroll, { passive: true }); return () => { cancelAnimationFrame(start); clearTimeout(t); removeEventListener('scroll', scroll) } }, []);
  useEffect(() => { document.body.style.overflow = (menu || study !== null) ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [menu, study]);
  const active = study === null ? null : projects[study];
  return <main id="main-content">
    {loader && <output className="loader"><div><strong>NISHKARSH.</strong><span>COORDINATING IDEAS INTO IMPACT.</span></div><i /></output>}
    <a href="#about" className="skip-link">Skip to content</a>
    <header className={`site-header ${scrolled ? 'is-scrolled' : ''}`}><a href="#home" className="brand"><span className="monogram">NC</span><span><strong>Nishkarsh Chaudhary</strong><small>Technical Project Coordinator</small></span></a><nav aria-label="Primary navigation">{['About', 'Experience', 'Projects', 'Expertise', 'Contact'].map((x, i) => <a key={x} href={`#${x.toLowerCase()}`}>{x}{i === 2 && <sup>+</sup>}</a>)}</nav><div className="header-actions"><a className="pill pill-small" href="mailto:nishkarsh541@gmail.com">Let&apos;s connect <ArrowUpRight /></a><button className="menu-button" onClick={() => setMenu(true)} aria-label="Open menu"><Menu /></button></div></header>
    <section className="hero" id="home"><div className="system-map" aria-hidden="true"><div className="grid-plane" /><span className="route route-a" /><span className="route route-b" /><i className="node node-a" /><i className="node node-b" /><i className="node node-c" /></div><div className="hero-copy"><p className="eyebrow">Technical delivery starts with clarity.</p><h1>Turning<br />complex ideas<br /><span>into delivered</span><br />products.</h1></div><div className="hero-aside"><p>I coordinate SaaS, ERP, logistics, marketing technology, blockchain, and AI-enabled products—from discovery through launch.</p><strong>Business goals, product decisions, and technical teams—aligned in one delivery system.</strong><div className="hero-actions"><a className="pill" href="#projects">Explore my work <ArrowUpRight /></a><a className="text-link" href="https://www.linkedin.com/in/nishkarsh-chaudhary-a08967225/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight /></a></div></div><div className="marquee"><div>ERP · LOGISTICS · SAAS · PRODUCT DELIVERY · AGILE · MARKETING TECHNOLOGY · BLOCKCHAIN · AI SYSTEMS · ERP · LOGISTICS · SAAS · PRODUCT DELIVERY · AGILE · MARKETING TECHNOLOGY · BLOCKCHAIN · AI SYSTEMS ·</div></div></section>
    <section className="intro section" id="about"><p className="section-label">[ ABOUT NISHKARSH ]</p><h2>I bring structure to ambitious digital products—translating requirements into <em>clear plans, aligned teams, testable outcomes,</em> and dependable releases.</h2><div className="intro-grid"><div className="stacked">CLARITY<br />COORDINATION<br />DELIVERY</div><div className="prose"><p>I work at the point where business goals become product behaviour—and product decisions become coordinated work for design, engineering, and QA.</p><p>My focus is simple: remove ambiguity, make dependencies visible, and help capable teams deliver with confidence.</p><a className="pill outline" href="#experience">My experience <ArrowUpRight /></a></div></div></section>
    <section className="metrics section" id="experience"><div className="metric-main"><b>10+</b><p>Cross-functional professionals coordinated across engineering, design, and QA</p></div><div className="metric-list"><div><b>5</b><span>SaaS modules delivered as one ecosystem</span></div><div><b>6 <small>months</small></b><span>Worksbuddy delivery timeline</span></div><div><b>5+</b><span>Blockchain and fintech projects coordinated</span></div><div><b>10+</b><span>International projects managed concurrently</span></div></div></section>
    <section className="work section" id="projects"><p className="section-label">[ SELECTED WORK ]</p><div className="section-heading"><h2>Products I helped<br />move forward</h2><p>Systems shaped through structured requirements, cross-functional coordination, and delivery discipline.</p></div><div className="projects">{projects.map((p, i) => <article className="project-card" key={p[1]}><div className="project-visual"><span>SYSTEM / {p[0]}</span><img src={projectImages[i][0]} alt={projectImages[i][1]} />{i===2&&<a className="source-link" href="https://worksbuddy.ai/" target="_blank" rel="noreferrer">Visit Worksbuddy <ArrowUpRight /></a>}</div><div className="project-copy"><span className="project-num">{p[0]} / 05</span><p className="project-type">{p[2]}</p><h3>{p[1]}</h3><p>{p[3]}</p><div className="tags">{p[4].map(t => <span key={t}>{t}</span>)}</div><button className="case-link" onClick={() => setStudy(i)}>View case study <ArrowUpRight /></button></div></article>)}</div></section>
    <section className="value section" id="expertise"><p className="section-label">[ HOW I CREATE VALUE ]</p><div className="section-heading"><h2>From ambiguity<br />to execution</h2><p>I connect business intent, product behaviour, technical execution, and measurable acceptance.</p></div><div className="strengths">{strengths.map(s => <article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><div><small><Check /> Clear delivery context</small><small><Check /> Testable outcomes</small></div></article>)}</div></section>
    <footer id="contact"><p className="section-label">[ START A CONVERSATION ]</p><h2>Have a complex<br />product to move?</h2><div className="footer-row"><a href="mailto:nishkarsh541@gmail.com">nishkarsh541@gmail.com <ArrowUpRight /></a><p>Available for project coordination, product operations, and technical delivery opportunities.</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Nishkarsh Chaudhary</span><a href="#home">Back to top ↑</a></div></footer>
    <div className={`overlay-menu ${menu ? 'open' : ''}`} aria-hidden={!menu}><button onClick={() => setMenu(false)} aria-label="Close menu"><X /></button><p>Navigate / 2026</p>{['Home', 'About', 'Experience', 'Projects', 'Expertise', 'Contact'].map(x => <a key={x} href={`#${x.toLowerCase()}`} onClick={() => setMenu(false)}>{x}<ArrowUpRight /></a>)}<div><span><i /> Available for opportunities</span><a href="mailto:nishkarsh541@gmail.com">Email</a><a href="https://www.linkedin.com/in/nishkarsh-chaudhary-a08967225/">LinkedIn</a><span>India · Remote</span></div></div>
    {active && <dialog open className="case-modal"><button className="modal-close" onClick={() => setStudy(null)}><X /> Close</button><div className="case-inner"><p className="section-label">CASE STUDY / {active[0]}</p><p className="project-type">{active[2]}</p><h2>{active[1]}</h2><p className="case-lead">{active[3]}</p><div className="case-columns"><div><h3>My role</h3><p>Requirements discovery, delivery coordination, workflow definition, acceptance criteria, dependencies, UAT, and release readiness.</p></div><div><h3>Delivery approach</h3><p>Turn ambiguity into shared decisions, break the system into testable behaviour, and keep delivery risks visible.</p></div><div><h3>Intended value</h3><p>A coherent, operable product experience with clearer decision-making and dependable delivery.</p></div></div><div className="tags">{active[4].map(t => <span key={t}>{t}</span>)}</div><p className="confidential">Selected details are generalized to respect client and product confidentiality.</p></div></dialog>}
  </main>
}
